In [118]:
import matplotlib.pyplot as plt
from scipy.optimize import leastsq
import numpy as np
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.linear_model import LogisticRegression

In [119]:
year=[[2008],[2009],[2010],[2011],[2012],[2013],[2014]]
yearall=[[2008],[2009],[2010],[2011],[2012],[2013],[2014],[2015],[2016]]
yearShow = range(2008,2017)
regr = linear_model.LinearRegression()

In [120]:
DE_x=[11070,6740,7800,24630,29545,36805,44465]
DE_y=[980 	2065 	5 	215 	1115 2990,5785]
DE_rate = []
DE_capacity =[]
for i in range(0,7):
    DE_rate.append(DE_y[i]/DE_x[i])
    DE_capacity.append(DE_x[i]-DE_y[i])


In [121]:
regr.fit(year, DE_capacity)
DE_capacity.append(regr.predict(2015))
DE_capacity.append(regr.predict(2016))
plt.scatter(yearShow,DE_capacity,color='blue',label="DE")
plt.plot(yearall,regr.predict(yearall),color='red',linewidth=2)

In [122]:
plt.xticks(())
plt.yticks(())
plt.show()

In [117]:
DE_capacity

[2775.0,
 2295.0,
 2465.0,
 3365.0,
 5025.0,
 5960.0,
 6995.0,
 array([ 7347.14285714]),
 array([ 8152.5])]

In [50]:
predict_outcome

array([ 0.89285941])

In [32]:
print len(y)

768


In [ ]:
x1 = np.array(x)  
y1 = np.array(y)

xishu = leastsq(err, p0, args=(x1,y1))

print xishu[0]