# The test for numpy

In [5]:
from numpy import *

* Random array

In [6]:
random.rand(4,4)

array([[ 0.12994843,  0.692     ,  0.37644594,  0.62268326],
       [ 0.24734433,  0.74573865,  0.92982083,  0.0756329 ],
       [ 0.68916837,  0.54079178,  0.31693679,  0.13998938],
       [ 0.48800738,  0.73064645,  0.75130802,  0.47103917]])

* convert to matrix

In [8]:
randMat = mat(random.rand(4,4))

In [9]:
randMat

matrix([[ 0.25620817,  0.70825618,  0.53204348,  0.824659  ],
        [ 0.62468179,  0.88916727,  0.32040714,  0.26617713],
        [ 0.93157678,  0.18850389,  0.28712794,  0.01002882],
        [ 0.39635926,  0.95394381,  0.18486165,  0.6099684 ]])

* the inversion of randMat

In [11]:
randMat.I

matrix([[-0.51133058, -1.17740261,  1.5013704 ,  1.18041202],
        [-0.51426393,  1.87350613, -1.07032662, -0.10469064],
        [ 1.97785656,  2.69419375, -0.71767888, -3.83789142],
        [ 0.53710927, -2.98146304,  0.91581907,  2.19926258]])

In [12]:
randMat*randMat.I

matrix([[  1.00000000e+00,  -4.44089210e-16,   1.11022302e-16,
           0.00000000e+00],
        [  0.00000000e+00,   1.00000000e+00,   2.77555756e-17,
          -3.33066907e-16],
        [ -4.94396191e-17,  -8.32667268e-17,   1.00000000e+00,
           1.11022302e-16],
        [  0.00000000e+00,   0.00000000e+00,  -1.11022302e-16,
           1.00000000e+00]])

### this represents there is much error

* unit matrix

In [14]:
eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])